Adicionando roteiro para viagem
campuscode/travelmatch pull request #1
Opened 2018-03-24 00:14 UTC by praganavictor

https://trello.com/c/WQQ6qd3a/9-viajante-adiciona-um-roteiro-ao-plano-de-viagem

2018-03-24 00:16 UTC, joaorsalmeida commented
Parece que tem conflitos para resolver ainda :(

2018-03-24 00:19 UTC, joaorsalmeida commented on app/controllers/itineraries_controller.rb
> +    @itinerary = Itinerary.new
Poderia ter sido criado assim: 
`@itinerary = @trip_plan.itineraries.build`

2018-03-27 20:54 UTC, zederson commented
Rodar o `rubocop`

2018-03-27 20:54 UTC, zederson requested changes

2018-03-27 20:54 UTC, zederson commented on app/controllers/itineraries_controller.rb
> +      flash[:notice] = "Você precisa preencher todos os campos."
aspas simples

2018-03-27 20:54 UTC, zederson commented on app/controllers/trip_plans_controller.rb
> +
linha em branco

2018-03-27 20:54 UTC, zederson commented on app/views/itineraries/new.html.erb
> +      <%= flash[:notice] %>
Seria legal colocar no `views/layouts` a parte que imprime o `flash`

2018-03-27 20:54 UTC, zederson commented on app/views/itineraries/new.html.erb
> +    <p><%= i %></p>
Seria legal formatar a mensagem de erro, igual esta logo a cima com o `flash[:notice]`

2018-03-27 20:54 UTC, zederson commented on app/views/itineraries/show.html.erb
> +  <%= flash[:notice] %>
imprimir o flash formatado com bootstrap

2018-03-27 20:54 UTC, zederson commented on app/views/trip_plans/index.html.erb
> +<% if flash.any? %>
Esse trecho esta repetido em várias páginas, seria legal fazer uma partial e usar no `app/views/layout`

2018-03-27 20:54 UTC, zederson commented on app/views/trip_plans/show.html.erb
> +  <div class="alert alert-success alert-dismissible fade show" role="alert">
mesmo comentário sobre partials

2018-03-27 20:54 UTC, zederson commented on spec/features/traveler_add_itinerary_spec.rb
> +    #i = Itinerary.create(location: 'Rio de janeiro', season: 'Carnaval', start_date: '20/12/2018', end_date: '30/12/2018', trip_plan_id: tp)
se não for usar, pode remover o comentário

2018-03-27 23:14 UTC, margarido approved these changes

2018-03-27 23:29 UTC, merged